// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNhAqBH43JMTjLTwsPKvdHt1RolxlW_tM',
    appId: '1:728682411782:web:3404bfea9546bfe34f1087',
    messagingSenderId: '728682411782',
    projectId: 'renosh-acb80',
    authDomain: 'renosh-acb80.firebaseapp.com',
    storageBucket: 'renosh-acb80.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmAj4z_c11wZpFGTDH0Qez2kAzLNvedJw',
    appId: '1:728682411782:android:119f6a2a23d168624f1087',
    messagingSenderId: '728682411782',
    projectId: 'renosh-acb80',
    storageBucket: 'renosh-acb80.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNhAqBH43JMTjLTwsPKvdHt1RolxlW_tM',
    appId: '1:728682411782:web:f2a13d1662b6a8864f1087',
    messagingSenderId: '728682411782',
    projectId: 'renosh-acb80',
    authDomain: 'renosh-acb80.firebaseapp.com',
    storageBucket: 'renosh-acb80.firebasestorage.app',
  );
}
