// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtWEl2pmE6ONGn-YBPc-w0caneZMPFZm0',
    appId: '1:62125287537:web:50e57adc824cfa966ed3d0',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    authDomain: 'renosh-4569b.firebaseapp.com',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD56pB08vR0v-52QFwa-O_BeK_5Q2QFeto',
    appId: '1:62125287537:android:2172da0e66acf3136ed3d0',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtWEl2pmE6ONGn-YBPc-w0caneZMPFZm0',
    appId: '1:62125287537:web:7248cc51ef9ff7586ed3d0',
    messagingSenderId: '62125287537',
    projectId: 'renosh-4569b',
    authDomain: 'renosh-4569b.firebaseapp.com',
    storageBucket: 'renosh-4569b.firebasestorage.app',
  );

}